# Generated by Django 5.2.4 on 2025-08-07 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boothNumber', models.IntegerField()),
                ('boothName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerName', models.CharField(max_length=50)),
                ('farmerBreif', models.TextField(max_length=200)),
                ('farmerImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_us.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='FarmersInBooths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_us.booths')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_us.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('productPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Farmers',
        ),
        migrations.AddField(
            model_name='farmerproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_us.products'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmerSpecialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_us.specializations'),
        ),
    ]
