# Generated by Django 5.2.4 on 2025-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_booths_farmer_farmerproducts_farmersinbooths_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemebers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=50)),
                ('memberPosition', models.CharField(max_length=50)),
                ('memberBreif', models.CharField(max_length=50)),
                ('memberPhoto', models.ImageField(upload_to='')),
            ],
        ),
    ]
