# Generated by Django 5.2.4 on 2025-08-12 09:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_teammemebers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThursdayMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateTime', models.DateTimeField(default=datetime.datetime(2025, 8, 14, 8, 0))),
                ('endDateTime', models.DateTimeField(default=datetime.datetime(2025, 8, 14, 15, 0))),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='productPrice',
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vission',
            name='vission',
            field=models.TextField(max_length=50),
        ),
        migrations.CreateModel(
            name='ProductPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productPrice', models.FloatField()),
                ('editDeadlineDateTime', models.DateTimeField(default=datetime.datetime(2025, 8, 14, 8, 0))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_us.products')),
            ],
            options={
                'unique_together': {('product', 'productPrice')},
            },
        ),
        migrations.DeleteModel(
            name='Hints',
        ),
        migrations.DeleteModel(
            name='OpsTeam',
        ),
    ]
