# Generated by Django 5.2.4 on 2025-08-17 08:31

import about_us.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_thursdaymarket_remove_products_productprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprices',
            name='editDeadlineDateTime',
            field=models.DateTimeField(default=about_us.models.get_next_thursday_8am),
        ),
        migrations.AlterField(
            model_name='thursdaymarket',
            name='endDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 21, 15, 0)),
        ),
        migrations.AlterField(
            model_name='thursdaymarket',
            name='startDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 21, 8, 0)),
        ),
    ]
