# Generated by Django 5.2 on 2025-04-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='null', upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
