# Generated by Django 5.2.4 on 2025-08-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('date', 'Date'), ('ceremony', 'Ceremonies'), ('visit', 'Visits')], default='date', max_length=20),
        ),
    ]
