# Generated by Django 5.2.4 on 2025-08-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50)),
                ('eventDescription', models.TextField(max_length=200)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('eventClosedRegistration', models.DateTimeField()),
                ('eventRegistrationStatus', models.CharField(choices=[('OPEN_FOR_REGISTRATION', 'OPEN_FOR_REGISTRATION'), ('CLOSED_REGISTRATION', 'CLOSED_REGISTRATION')], max_length=50)),
                ('ad', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('eventName', 'startDate', 'endDate')},
            },
        ),
    ]
