# Generated by Django 5.2.4 on 2025-08-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventRegistrationStatus',
            field=models.CharField(choices=[('OPEN_FOR_REGISTRATION', 'Open for registration'), ('CLOSED_REGISTRATION', 'Closed registration')], max_length=50),
        ),
    ]
