# Generated by Django 5.2.4 on 2025-08-17 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_event_eventregistrationstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='main_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('ceremony', 'Ceremonies'), ('visit', 'Visits')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blogs.blog')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
