# Generated by Django 5.2.4 on 2025-08-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_rename_image_blog_main_image_blog_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
