# Generated by Django 5.2.4 on 2025-08-03 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendeeName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField()),
            ],
            options={
                'unique_together': {('attendeeName', 'phoneNumber')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50)),
                ('eventDescription', models.TextField(max_length=200)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('eventClosedRegistartion', models.DateTimeField()),
                ('eventRegistrationStatus', models.CharField(choices=[('OPEN_FOR_REGISTRATION', 'OPEN_FOR_REGISTRATION'), ('CLOSED_REGISTRATION', 'CLOSED_REGISTRATION')], max_length=50)),
                ('eventStatus', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], max_length=50)),
                ('ad', models.BooleanField()),
            ],
            options={
                'unique_together': {('eventName', 'startDate', 'endDate')},
            },
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendeeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactus.attendee')),
                ('eventName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactus.event')),
            ],
            options={
                'unique_together': {('attendeeName', 'eventName')},
            },
        ),
    ]
