# Generated by Django 5.2.4 on 2025-08-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50)),
                ('eventDescription', models.TextField(max_length=200)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('eventClosedRegistartion', models.DateTimeField()),
                ('ad', models.BooleanField()),
            ],
            options={
                'unique_together': {('eventName', 'startDate', 'endDate')},
            },
        ),
    ]
