# Generated by Django 5.2.4 on 2025-08-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
