# Generated by Django 5.2.4 on 2025-08-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_attendee_event_eventattendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventStatus',
        ),
        migrations.AlterField(
            model_name='event',
            name='eventRegistrationStatus',
            field=models.CharField(choices=[('OPEN_FOR_REGISTRATION', 'OPEN_FOR_REGISTRATION'), ('CLOSED_REGISTRATION', 'CLOSED_REGISTRATION')], default='OPEN_FOR_REGISTRATION', max_length=50),
        ),
    ]
