# Generated by Django 5.2.4 on 2025-08-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_remove_event_eventstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventClosedRegistartion',
            new_name='eventClosedRegistration',
        ),
    ]
